version: 2

models:
  - name: int_crime_data
    description: "Intermediate model for cleaned and transformed crime data"
    columns:
      - name: CRIME_ID
          - not_null
      - name: CRIME_DATE
        tests:
          - not_null
      - name: REPORTED_BY
        tests:
          - not_null
      - name: FALLS_WITHIN
        tests:
          - not_null
      - name: LONGITUDE
      - name: LATITUDE
      - name: UPDATED_LOCATION
        tests:
          - not_null
      - name: LSOA_CODE
      - name: LSOA_NAME
      - name: CRIME_TYPE
        tests:
          - not_null
      - name: LAST_OUTCOME
      - name: CONTEXT
      - name: LAST_UPDATED
        description: "Timestamp when the record was staged into the model"
        tests:
          - not_null