SELECT 
    CRIME_DATE,
    REPORTED_BY,
    UPDATED_LOCATION AS LOCATION,
    COUNT(*) AS CRIME_COUNT
FROM 
    {{ ref('int_crime_data')}}
GROUP BY 
    ALL
ORDER BY 
    REPORTED_BY, CRIME_COUNT DESC