SELECT
    CRIME_DATE,
    REPORTED_BY,
    CRIME_TYPE,
    UPDATED_LOCATION AS LOCATION,
    COUNT(*) AS CRIME_COUNT
FROM 
    {{ ref('int_crime_data') }}
GROUP BY 
    CRIME_DATE,
    REPORTED_BY,
    CRIME_TYPE,
    UPDATED_LOCATION
ORDER BY 
    REPORTED_BY,
    CRIME_COUNT DESC