{{ config(
    materialized = 'incremental'
) }}

WITH RAW_DATA AS (
  SELECT 
    * 
  FROM {{ source('RAW_DATA', 'SOURCES_CRIME_DATA') }}
)

SELECT
  CRIME_ID,
  MONTH,
  REPORTED_BY,
  FALLS_WITHIN,
  LONGITUDE,
  LATITUDE,
  LOCATION,
  LSOA_CODE,
  LSOA_NAME,
  CRIME_TYPE,
  LAST_OUTCOME,
  NULLIF(CONTEXT, '') AS CONTEXT,
  CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM RAW_DATA
WHERE CRIME_ID IS NOT NULL

{% if is_incremental() %}
WHERE CURRENT_TIMESTAMP() > (SELECT MAX(LAST_UPDATED) FROM {{ this }})
{% endif %}